name: JeremyEssentials
version: '${project.version}'
main: de.devlucas.jeremyessentials.JeremyEssentials
api-version: '1.20'
commands:
  gm:
    aliases: [gamemode]
  cmdspy:
    aliases: [commandspy]
  help:
  heal:
  msg:
  support:
  godmode:
  cc:
    aliases: [chatclear]
  globalmute:
    aliases: [gb]
  fly:
  tp:
    aliases: [teleport]
  feed:
  ec:
  wb:
  invsee:
  repair:
  whois:
  tpa:
  tpaccept:
  tpdeny:
  kick: